version: '1.0'
services: 
  tensorflowrealm:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./tensorflowrealm:/tensorflowrealm
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]